name: tests
on:
  push:
  workflow_dispatch:

env:
  # rel, pre, mod
  OCVER: pre

jobs:
  test-and-cover:
    name: macOS XCODE5
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        run : |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          sudo systemsetup -settimezone "Asia/Shanghai"

      #- uses: brokeyourbike/ocvalidate-action@v0.2
      #  with:
      #    opencore-version: '0.8.6'
      #    release: true
      #
      #- run: |
      #    ocvalidate "EFI/OC/config.plist" || exit 1
      #    ocvalidate "EFI/OC/config_iGPU.plist" || exit 1
      #    ocvalidate "EFI/OC/config_RX5700XT.plist" || exit 1
      #    ocvalidate "EFI/OC/config_RX5700XT&iGPU.plist" || exit 1

      - name: Get OC-Mod
        run: |
          # brew install jq # Warning: jq 1.7.1 is already installed and up-to-date.

          if [ $OCVER == 'rel' ]; then
            url="https://api.github.com/repos/acidanthera/OpenCorePkg/releases/latest"
          elif [ $OCVER == 'pre' ]; then
            url="https://api.github.com/repos/dortania/build-repo/releases/latest"
          else
            url="https://api.github.com/repos/wjz304/OpenCore_NO_ACPI_Build/releases/latest"
          fi

          ocdownloadurl=$(curl -L ${url} | jq -r .assets[1].browser_download_url)
          curl -L ${ocdownloadurl} -o oc.zip
          unzip oc.zip -d oc

      - name: OC Validate
        run: |
          oc/Utilities/ocvalidate/ocvalidate "EFI/OC/config.plist" || exit 1
          oc/Utilities/ocvalidate/ocvalidate "EFI/OC/config_iGPU.plist" || exit 1
          oc/Utilities/ocvalidate/ocvalidate "EFI/OC/config_RX5700XT.plist" || exit 1
          oc/Utilities/ocvalidate/ocvalidate "EFI/OC/config_RX5700XT&iGPU.plist" || exit 1

      #- name: Delete workflow runs
      #  uses: Mattraks/delete-workflow-runs@v2
      #  with:
      #    retain_days: 1
      #    keep_minimum_runs: 3